#!/usr/bin/env python3
"""Annotate transcript comprehension errors with a local Hugging Face model."""
import argparse
import json
import sys
from pathlib import Path
from typing import Any, Iterator
import torch


# SYSTEM_PROMPT = """Compare the segment generated by a speech translation model with the English source. Annotate only errors in the segment generated by the speech translation model that cause or are likely to cause a meaningful difference from the source. To help you with this task, you can refer to the automatic backtranslation (in English) of the speech translation output.  Do not annotate harmless wording, punctuation, or stylistic differences.
# For each error, return:
# - span: the exact, contiguous text from the segment generated by the speech translation model that contains the error;
# - explanation: a concise explanation of why it differs from the reference;
# - harmfulness: an integer from 1 to 5 estimating how likely the error causes harm beyond the misunderstanding itself. Harm includes needing correction or apology, offense, embarrassment, laughter, or risk if acted upon. 1 means very unlikely; 5 means very likely.
# Return only a JSON object matching this schema:
# {"annotations":[{"span":"exact speech translation output text","explanation":"concise explanation","harmfulness":1}]}
# Return {"annotations":[]} when there are no qualifying errors."""

SYSTEM_PROMPT = """Compare the segment generated by a speech translation model with the English source. Annotate only errors in the segment generated by the speech translation model that cause or are likely to cause a meaningful difference from the source. Do not annotate harmless wording, paraphrasing, punctuation, or stylistic differences. Examples of harmful errors include:
- the translation gives a person the wrong identity, gender, role, relationship, or characteristics;
- a proper name is mishandled, a name is declined into the wrong gender, or the output is disrespectful to a person or group;
- the error introduces explicit, absurd or unintentionally funny content;
- the output is shocking or unexpected, or it conveys a false or opposite message that still sounds plausible;
- the error has an immediate real-world consequence in this situation, beyond the general risk of being misinformed.
For each error, return:
- span: the exact, contiguous text from the segment generated by the speech translation model that contains the error;
- explanation: a concise explanation of why it differs from the reference;
- harmfulness: an integer from 1 to 5 estimating how likely the error causes harm beyond the misunderstanding itself. Harm includes needing correction or apology, offense, embarrassment, laughter, or risk if acted upon. 1 means very unlikely; 5 means very likely.
Return only a JSON object matching this schema:
{"annotations":[{"span":"exact speech translation output text","explanation":"concise explanation","harmfulness":1}]}
Return {"annotations":[]} when there are no qualifying errors."""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True, help="Input JSONL file.")
    parser.add_argument("--output", type=Path, required=True, help="Output JSONL file.")
    parser.add_argument(
        "--model",
        default="Qwen/Qwen3-4B-Instruct-2507",
        help="Local model path or Hugging Face model ID for text generation.",
    )
    parser.add_argument(
        "--device",
        choices=("auto", "cpu", "cuda"),
        default="auto",
        help="Inference device (default: auto).",
    )
    parser.add_argument("--max-new-tokens", type=int, default=2048)
    parser.add_argument("--quantize", default=False, action='store_true')
    return parser.parse_args()


def jsonl_records(path: Path) -> Iterator[tuple[int, dict[str, Any]]]:
    with path.open(encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            if not line.strip():
                continue
            try:
                record = json.loads(line)
            except json.JSONDecodeError as error:
                raise ValueError(f"{path}:{line_number}: invalid JSON") from error
            if not isinstance(record, dict):
                raise ValueError(f"{path}:{line_number}: expected a JSON object")
            yield line_number, record


def prompt_for(record: dict[str, Any]) -> str:
    required_fields = (
        "original_segment", #    "madlad_translation",
        "resegmented_transcript",
    )
    missing = [field for field in required_fields if not isinstance(record.get(field), str)]
    if missing:
        raise ValueError(f"missing or invalid string field(s): {', '.join(missing)}")
    # f"backtranslation into English of the speech translation model output: {record['madlad_translation']}\n"
    return (
        f"{SYSTEM_PROMPT}\n\n"
        f"segment generated by the speech translation model: {record['original_segment']}\n"
        f"English source: {record['resegmented_transcript']}"
    )


def extract_json(response: str) -> dict[str, Any]:
    start = response.find("{")
    end = response.rfind("}")
    if start == -1 or end == -1 or end < start:
        raise ValueError("model response contains no JSON object")
    try:
        annotation = json.loads(response[start : end + 1])
    except json.JSONDecodeError as error:
        print("Invalid JSON: ", response[start : end + 1])
        return {"annotations": []}
    if not isinstance(annotation, dict) or not isinstance(annotation.get("annotations"), list):
        raise ValueError("model response must be an object with an annotations list")
    for item in annotation["annotations"]:
        if not isinstance(item, dict):
            raise ValueError("each annotation must be an object")
        if not isinstance(item.get("span"), str) or not isinstance(item.get("explanation"), str):
            raise ValueError("each annotation requires string span and explanation fields")
        rating = item.get("harmfulness")
        if not isinstance(rating, int) or isinstance(rating, bool) or not 1 <= rating <= 5:
            raise ValueError("annotation harmfulness must be an integer from 1 to 5")
    return annotation


class LocalAnnotator:
    def __init__(self, model_name: str, device: str, max_new_tokens: int, quantize: bool) -> None:
        from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline, BitsAndBytesConfig
        if max_new_tokens < 1:
            raise ValueError("--max-new-tokens must be at least 1")
        device_argument = -1
        if device == "cuda":
            device_argument = 0
        elif device == "auto":
            try:
                import torch
                device_argument = 0 if torch.cuda.is_available() else -1
            except ImportError:
                pass
        if quantize:
            bnb_config = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_quant_type="nf4", bnb_4bit_compute_dtype=torch.bfloat16, bnb_4bit_use_double_quant=True,)
        else:
            bnb_config = None
        tokenizer = AutoTokenizer.from_pretrained(model_name)
        model = AutoModelForCausalLM.from_pretrained(model_name, quantization_config=bnb_config, dtype=torch.bfloat16, device_map="auto").eval()
        self.generator = pipeline(
            "text-generation", model=model, tokenizer=tokenizer # , device=device_argument
        )
        self.max_new_tokens = max_new_tokens

    def annotate(self, record: dict[str, Any]) -> dict[str, Any]:
        prompt = self.generator.tokenizer.apply_chat_template(
            [
                {"role": "system", "content": "You are an expert evaluator of speech-recognition comprehension errors. You produce only valid JSON outputs to answer to the user."},
                {"role": "user", "content": prompt_for(record)},
            ],
            tokenize=False,
            add_generation_prompt=True,
        )
        print(prompt)
        with torch.inference_mode():
            result = self.generator(
              prompt,
              do_sample=False,
              max_new_tokens=self.max_new_tokens,
              return_full_text=False,
            )
        return extract_json(result[0]["generated_text"])


def main() -> None:
    args = parse_args()
    annotator = LocalAnnotator(args.model, args.device, args.max_new_tokens, args.quantize)
    with args.output.open("w", encoding="utf-8") as output:
        for line_number, record in jsonl_records(args.input):
            try:
                annotation = annotator.annotate(record)
            except ValueError as error:
                raise ValueError(f"{args.input}:{line_number}: {error}") from error
            output_record = {**record, "annotations": annotation["annotations"]}
            output.write(json.dumps(output_record, ensure_ascii=False) + "\n")


if __name__ == "__main__":
    try:
        main()
    except (FileNotFoundError, OSError, RuntimeError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        raise SystemExit(2)

